# Makefile for the main HotDrink library.

include Makefile.common
include Makefile.js

##################################################
# mandatory configuration

TITLE := hotdrink

##################################################
# optional configuration

MAIN := $(TITLE).js
MAINPLUS := $(TITLE)-plus.js

SRCDIR := lib
SOURCES := \
	utility/prototype-form-ex.js \
	utility/debug.js \
	utility/stdlib.js \
	utility/namespace.js \
	concept/model/behavior.js \
	concept/model/value.js \
	concept/view/ast.js \
	concept/view/behavior.js \
	concept/view/builder.js \
	concept/view/controller.js \
	graph/cgraph.js \
	graph/sgraph.js \
	graph/solver.js \
	graph/egraph.js \
	graph/evaluator.js \
	behavior/enablement.js \
	model.js \
	controller/model.js \
	driver.js

HEADERS := \
  utility/debug.m4.js

OBJDIR := build

THIRD_PARTY_SOURCES := \
	test/prototype.js

DOCDIR := doc

