# I am a starting template for a JavaScript library Makefile. Copy me!

include Makefile.common
include Makefile.js

##################################################
# mandatory configuration

TITLE := hotdrink-test

##################################################
# optional configuration

MAIN := $(TITLE).js
MAINPLUS := $(TITLE)-plus.js

SRCDIR := test
SOURCES := \
	common/hello_world.js \
	common/resize_image.js \
	common/save_image.js \
	common/enforced_minmax.js \
	common/grouped_options.js \
	model/value.js \
	model/enablement.js 

HEADERS := \

OBJDIR := build

THIRD_PARTY_SOURCES := \

DOCDIR := doc

