# Makefile for the main HotDrink library.

include Makefile.common
include Makefile.js

##################################################
# mandatory configuration

TITLE := hotdrink

##################################################
# optional configuration

MAIN := $(TITLE).js
MAINPLUS := $(TITLE)-plus.js

SRCDIR := lib
SOURCES := \
	utility/debug.js \
	utility/stdlib.js \
	utility/namespace.js \
	concept/model/behavior.js \
	concept/model/value.js \
	concept/view/ast.js \
	concept/view/behavior.js \
	concept/view/builder.js \
	concept/view/controller.js \
	model/graph/cgraph.js \
	model/graph/solver.js \
	model/graph/sgraph.js \
	model/graph/evaluator.js \
	model/graph/egraph.js \
	model/behavior/enablement.js \
	model/model.js \
	model/controller.js \
	model/factory.js \
	bindings/behavior/value.js \
	bindings/behavior/enablement.js \
	bindings/html/common.js \
	bindings/html/checkbox.js \
	bindings/html/checkboxGroup.js \
	bindings/html/radioGroup.js \
	bindings/html/selectOne.js \
	bindings/html/selectMany.js \
	bindings/html/text.js \
	bindings/html/number.js \
	bindings/html/html.js \
	bindings/controller.js \
	driver.js

HEADERS := \
  utility/debug.m4.js

OBJDIR := build

THIRD_PARTY_SOURCES := \
	test/prototype.js

DOCDIR := doc

