# Makefile for the main HotDrink library.

include Makefile.common
include Makefile.js

##################################################
# mandatory configuration

TITLE := hotdrink

##################################################
# optional configuration

MAIN := $(TITLE).js
MAINPLUS := $(TITLE)-plus.js

SRCDIR := lib
SOURCES := \
	utility/prototype-form-ex.js \
	utility/debug.js \
	utility/stdlib.js \
	utility/namespace.js \
	concept/model/behavior.js \
	concept/model/value.js \
	concept/view/ast.js \
	concept/view/behavior.js \
	concept/view/builder.js \
	concept/view/controller.js \
	graph/cgraph.js \
	graph/sgraph.js \
	graph/solver.js \
	graph/egraph.js \
	graph/evaluator.js \
	behavior/enablement.js \
	model.js \
	controller/model.js \
	controller/factory.js \
	controller/behavior/value.js \
	controller/behavior/enablement.js \
	controller/view/common.js \
	controller/view/html.js \
	controller/view/html/common.js \
	controller/view/html/row.js \
	controller/view/html/column.js \
	controller/view/html/checkbox.js \
	controller/view/html/checkboxGroup.js \
	controller/view/html/commandButton.js \
	controller/view/html/dropdown.js \
	controller/view/html/number.js \
	controller/view/html/radioGroup.js \
	controller/view/html/selectMany.js \
	controller/view/html/selectOne.js \
	controller/view/html/text.js \
	controller/view/html/build.js \
	controller.js \
	parser/parsec.js \
	parser/expr_parser.js \
	parser/model_parser.js \
	parser/view_parser.js \
	driver.js

HEADERS := \
  utility/debug.m4.js

OBJDIR := build

THIRD_PARTY_SOURCES := \
	test/js/prototype.js

DOCDIR := doc

