# Makefile for HotDrink tests.

include $(MAKEDIR)/Makefile.common
include $(MAKEDIR)/Makefile.js

##################################################
# mandatory configuration

TITLE := hotdrink-test

##################################################
# optional configuration

MAIN := $(TITLE).js
MAINPLUS := $(TITLE)-plus.js

SRCDIR := test/qunit
SOURCES := \
  common/patterns.js \
	test/patterns.js \
	common/hello_world.js \
	common/circle.js \
	common/resize_image.js \
	common/save_image.js \
	common/enforced_minmax.js \
	common/grouped_options.js \
	model/value.js \
	model/enablement.js \
	parser/model.js

HEADERS := \

OBJDIR := build

THIRD_PARTY_SOURCES := \

DOCDIR := doc

